In [ ]:
# numpy陣列建立方式
import numpy as np

a = np.array([2, 23, 4])
print(a)
a = np.array([2, 23, 4], dtype=np.float)
print("\n", a.dtype)
a = np.array([[2, 23, 4], [2, 32, 4]])
print("\n", a)
a = np.zeros((3, 4))
print("\n", a)
a = np.ones((3, 4), dtype=np.int)
print("\n", a)
a = np.empty((3, 4))
print("\n", a)
a = np.arange(10, 20, 2)
print("\n", a)
a = np.arange(1, 13)
print("\n", a)
print(a.reshape((3, 4)))
a = np.linspace(1, 10, 20)
print("\n", a)

# reshape--改變維度的大小
a = np.arange(12).reshape(2, 6) #二維
print(a)
a = np.arange(24).reshape(2,4,3) #三維
print(a)

In [2]:
import numpy as np
a=np.arange(24).reshape(2,4,3)
print(a)
np.set_printoptions(threshold=20)
print(np.arange(20))
np.set_printoptions(threshold=15)
print(np.arange(20))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2 ... 17 18 19]


In [ ]:
# numpy陣列基本運算
import numpy as np
a = np.array([10, 20, 30, 40])
b = np.arange(1, 5)

c = a + b
print(c, "\n")
c = a - b
print(c, "\n")
c = a * b
print(c, "\n")
c = a / b
print(c, "\n")
c = b**2
print(c, "\n")
c = 10 * np.sin(a)
print(c, "\n")
print(b < 3)

In [ ]:
# numppy二維矩陣的dot乘法 -- 不理解
a = np.array([[1, 1], [0, 1]])
b = np.arange(4).reshape((2, 2))
print(a, "\n", b, sep="")

c_dot = np.dot(a, b)
print("\n", c_dot, sep="")

c_dot = a.dot(b)
print("\n", c_dot, sep="")

In [ ]:
import numpy as np

a = np.random.random((2, 4))
b = np.random.randn(2, 4)
print(a, "\n")
print(b, "\n")
print(a.sum(), "\n")
print(a.min(), "\n")
print(a.max(), "\n")

# axis=0，以列为查找单元，axis=1，以行为查找单元
print("a=", a)
print("sum=", a.sum(axis=1))
print("min=", a.min(axis=0))
print("max=", a.max(axis=1))

In [ ]:
import numpy as np
A = np.arange(2, 17).reshape((3, 5))

# array([[ 2, 3, 4, 5]
#        [ 6, 7, 8, 9]
#        [10,11,12,13]])
print(A)
print(A.argmin())  # 0
print(A.argmax())  # 11
print(A.mean())  #平均數(sum/個數)
print(np.median(A))  #中位數
print(np.average(A))  #加權平均數

In [ ]:
# numpy矩陣的轉置
import numpy as np
A = np.arange(14, 2, -1).reshape((3, 4))

# array([[14, 13, 12, 11],
#       [10,  9,  8,  7],
#       [ 6,  5,  4,  3]])

print(np.sort(A))

# array([[11,12,13,14]
#        [ 7, 8, 9,10]
#        [ 3, 4, 5, 6]])
print(np.transpose(A))
print(A.T)
# array([[14,10, 6]
#        [13, 9, 5]
#        [12, 8, 4]
#        [11, 7, 3]])
# array([[14,10, 6]
#        [13, 9, 5]
#        [12, 8, 4]
#        [11, 7, 3]])

In [ ]:
import numpy as np
A = np.array([1, 1, 1])
B = np.array([2, 2, 2])

# vstack--vertical(垂直合併)
print(np.vstack((A, B)))
print(np.stack(np.vstack((A, B)), axis=1))
# print(np.stack(np.vstack((A,B)),axis=0))

# hstack--herizontal(水平合併)
print(np.hstack((A, B)))

In [ ]:
import numpy as np

a = np.arange(4)
b = a
c = a
d = b
a[0] = 11
print(a, b, c, d)
d[1:3] = [22, 33]
print(a, b, c, "\n")

# a.copy會複製一個全新而沒有關聯性的陣列
b = a.copy()
print(a, b)
a[3] = 44
print(a, b)